### ISSUE TITLE
Create a new tag for the latest release

### ISSUE THREAD

**Issue by Gocnak** [WyriHaximus/github-action-next-release-version#5]
Hi, I'm interested in using this action and the GitHub actions marketplace recommends using the `1.0.0` tag, which is out of date (since it uses set-output still).

Could you please create a new tag to use the new env var outputs on master? It's best practice to lock to a tag instead of using `@master` for the version.

Thank you!

**Comment by WyriHaximus** [comment]
Hey @Gocnak thank you for bringing this up. Looking at the repository I'm not sure why the current state wasn't released back when I updated it. It has that fix, plus all the changes to make `@v1` targeting common within the Actions ecosystem possible. Also just updated the readme with that `@v1` targeting, so I'll release it now.

**Comment by WyriHaximus** [comment]
`v1(.1(.0))` is out and listed on marketplace as the latest version.

**Comment by Gocnak** [comment]
Thank you for the quick fix and making the action! Cheers 👍
